version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(go):"

  - package-ecosystem: pip
    directory: /clients/python
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(py):"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(ci):"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(docker):"
